name: verificando no PR

on:
  pull_request:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: brnorg/actions-brnorg/.github/workflows/liberaoubarrapr.yml@main



